{% set version = "0.3.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-sftime
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sftime_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sftime/sftime_{{ version }}.tar.gz
  sha256: adadd4d5f6ef388b7145d83896fcc020ad03475eae9d86a100d6207611ded7b7

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-sf >=1.0.7
  run:
    - r-base
    - r-sf >=1.0.7

test:
  commands:
    - $R -e "library('sftime')"           # [not win]
    - "\"%R%\" -e \"library('sftime')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=sftime
  license: Apache-2.0
  summary: Classes and methods for spatial objects that have a registered time column, in particular for irregular spatiotemporal data. The time column can be of any type, but needs to be ordinal. Regularly laid out spatiotemporal data (vector or raster data cubes) are handled by package 'stars'.
  license_family: APACHE
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
